### PR TITLE
feat: allow custom retention days for extended auditing policy

### PR DESCRIPTION
**Pull request by helenakallekleiv**
Added feature: Variable `extended_auditing_policy_retention_in_days` with default `0` retention days.

Plus some minor formatting.

### CODE REVIEW

**Comment by helenakallekleiv** [comment]
Tests pass 👍🏼 Ready for review.

**Comment by helenakallekleiv** [comment]
Could potentially be a `refactor` as the default in the resource documentation is set to `0`, but as this enables users to set custom retention days it qualifies as a feature.

**Review by sebastianlolv — APPROVED** [review]
Tests pass and LGTM 👍

**Comment by hknutsen** [comment]
Unsure if this policy actually does anything when we're sending logs to Log Analytics 🤔 

If sending audit logs to Log Analytics, then the retention policy is decided by the target Log Analytics workspace.

If sending audit logs to Storage, then the retention policy is decided by the auditing policy (which is what is configured in this PR).

Will try to get back with a reference for this statement 🙂

**Pull request merged**
