### PR TITLE
feat!: don't create failover groups

### LINKED ISSUE #102: feat!: remove failover groups
Module should only create resources that should always be created.

Since failover groups are optional, they should be created outside the module instead.

### PR DESCRIPTION
**Pull request by hknutsen**
Fixes #102

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests pass :tada:

**Comment by hknutsen** [comment]
@helenakallekleiv @kov117 Let me know if you object to this change.

**Comment by helenakallekleiv** [comment]
@hknutsen I agree that optional resources should be created outside of the modules, so this looks good to me. Just gonna run a test first 👍🏼 

A thought, does this also apply to the sub modules, or does it for now only apply to the main modules?

**Comment by hknutsen** [comment]
I think we should create stricter rules for what to be created, both for resources and submodules.

**Review by helenakallekleiv — APPROVED** [review]
Tests pass ⭐

**Pull request merged**
